name: Dependabot Metrics

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TOKEN: ${{ secrets.COLLECT_ANALYCTS }}
      ORGANIZATION: ${{ secrets.ORGANIZATION }}
      WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
    
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      - name: Test the basic usage
        run: |
          python3 scripts/dependabot_metrics.py --org $ORGANIZATION --token $TOKEN | python3 scripts/slack_webhook.py --webhook $WEBHOOK